-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE (CATEGORY LIKE '과자' OR CATEGORY LIKE '국' 
       OR CATEGORY LIKE '김치' OR CATEGORY LIKE '식용유') 
AND PRICE = 
(SELECT MAX(PRICE) FROM FOOD_PRODUCT B WHERE A.CATEGORY = B.CATEGORY)
ORDER BY PRICE DESC;