-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A, PATIENT B, DOCTOR C
WHERE 
    A.PT_NO = B.PT_NO 
AND 
    A.MDDR_ID = C.DR_ID
AND A.APNT_CNCL_YMD IS NULL
AND TO_CHAR(APNT_YMD,'YYYYMMDD') = '20220413'
AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;