-- 코드를 입력하세요
-- 기본경로 게시판ID 파일ID파일명 파일확장자
SELECT 
    '/home/grep/src/' || A.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
FROM USED_GOODS_BOARD A, USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID
AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;
